version: '3.8'
services:
  app:
    build:
      dockerfile: ./dockerfile
      context: .
    volumes:
      - .:/src
      - venv_volume:/src/.venv
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["poetry", "run", "gunicorn", "src.main:app", "--config", "src/gunicorn/config.py"]
    extra_hosts:
      - localhost:host-gateway

  db:
    image: postgres:16.3
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_volume:
  venv_volume:
